image: docker:latest

variables:
  DOCKER_DRIVER: overlay

stages:
  - build
  - release
  - deploy

variables:
  CONTAINER_BUILD_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

services:
  - docker:dind

before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t $CONTAINER_BUILD_IMAGE .
    - docker push $CONTAINER_BUILD_IMAGE

release:
  stage: release
  script:
    - docker pull $CONTAINER_BUILD_IMAGE
    - docker tag $CONTAINER_BUILD_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master

deploy:
  stage: deploy
  script:
    - docker pull $CI_REGISTRY/jteppinette/stackahoy
    - docker run --rm $CI_REGISTRY/jteppinette/stackahoy deploy -t $STACKAHOY_TOKEN -b master -r 58dd0b8d16cc4e0900af8f8e --skip-delivery
  only:
    - master
