export SMTP_SERVER=$MAILGUN_SMTP_SERVER
export SMTP_PORT=$MAILGUN_SMTP_PORT
export SMTP_LOGIN=$MAILGUN_SMTP_LOGIN
export SMTP_PASSWORD=$MAILGUN_SMTP_PASSWORD
export SMTP_DOMAIN=$MAILGUN_DOMAIN

export STORAGE_ACCESS_KEY_ID=$BUCKETEER_AWS_ACCESS_KEY_ID
export STORAGE_SECRET_ACCESS_KEY=$BUCKETEER_AWS_SECRET_ACCESS_KEY
export STORAGE_BUCKET=$BUCKETEER_BUCKET_NAME
export STORAGE_URL=https://${BUCKETEER_BUCKET_NAME}.s3.amazonaws.com
