version: "3"

volumes:
  db:
  media:

services:

  app:
    build: .
    ports:
      - 8000:80
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    links:
      - db
    volumes:
      - media:/app/media

  db:
    image: postgres:9.6
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=secret
    volumes:
      - db:/var/lib/postgresql/data
