version: "3"

volumes:
  db:
  storage:

services:

  app:
    build: .
    ports:
      - 8000:80
    environment:
      - DEVELOPMENT=True
      - DATABASE_URL=postgres://db:secret@db:5432/db
      - SMTP_SERVER=mail
      - SMTP_PORT=1025
      - STORAGE_URL=http://storage:9000
      - STORAGE_BUCKET=storage
    links:
      - db
      - storage
      - mail

  db:
    image: postgres:10
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=secret
    volumes:
      - db:/var/lib/postgresql/data

  storage:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: access-key-id
      MINIO_SECRET_KEY: secret-access-key
    command: server /data
    volumes:
      - storage:/data

  mail:
    image: schickling/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"
