version: "3"

volumes:
  db:
  minio:

services:

  app:
    build: .
    ports:
      - 8000:80
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - MINIO_SERVER=minio:9000
      - MINIO_BUCKET=water-dragon
      - MAIL_HOST=mail
      - MAIL_PORT=1025
    links:
      - db
      - minio
      - mail

  db:
    image: postgres:9.6
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=secret
    volumes:
      - db:/var/lib/postgresql/data

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: access-key
      MINIO_SECRET_KEY: secret-key
    command: server /data
    volumes:
      - minio:/data

  mail:
    image: schickling/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"
