# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 01:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_minio.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CarbonCopyAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carbon Copy Address',
                'verbose_name_plural': 'Carbon Copy Addresses',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=160)),
                ('planner_name', models.CharField(max_length=80)),
                ('planner_mobile', models.CharField(max_length=80)),
                ('planner_email', models.EmailField(max_length=254)),
                ('president_email', models.EmailField(max_length=254)),
                ('sober_monitors', models.TextField()),
                ('expected_guest_count', models.IntegerField()),
                ('exclusivity', models.CharField(choices=[(b'Invitation Only', b'Invitation Only'), (b'Open to the public', b'Open to the public'), (b'Open to Faculty, Staff, Students', b'Open to Faculty, Staff, Students')], max_length=80)),
                ('alcohol_distribution', models.TextField(blank=True, null=True)),
                ('entry', models.CharField(choices=[(b'Yes', b'Yes'), (b'No', b'No')], max_length=80)),
                ('entry_description', models.CharField(max_length=160)),
                ('co_sponsored_description', models.TextField(blank=True, null=True)),
                ('transportation', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reach', models.CharField(choices=[(b'Nationals', b'Nationals'), (b'Administrator', b'Administrator'), (b'Host', b'Host')], max_length=80)),
                ('violation', models.CharField(choices=[(b'Underage Drinking', b'Underage Drinking'), (b'Stealing', b'Stealing'), (b'Vandalism', b'Vandalism'), (b'Violence', b'Violence'), (b'Probation', b'Probation'), (b'Other', b'Other')], max_length=80)),
                ('other', models.CharField(blank=True, max_length=80, null=True)),
                ('administrator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='api.Administrator')),
            ],
        ),
        migrations.CreateModel(
            name='GuestRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=django_minio.storage.MinioStorage(), upload_to=b'images/guests')),
                ('date_time_taken', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='api.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('administrator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='api.Administrator')),
            ],
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('gender', models.CharField(choices=[(b'Male', b'Male'), (b'Female', b'Female')], max_length=80)),
                ('dob', models.DateField()),
            ],
            options={
                'verbose_name': 'Identity',
                'verbose_name_plural': 'Identities',
            },
        ),
        migrations.CreateModel(
            name='Invitee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('gender', models.CharField(choices=[(b'Male', b'Male'), (b'Female', b'Female')], max_length=80)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitees', to='api.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Nationals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Nationals',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(choices=[(b'Interior Sweep', b'Interior Sweep'), (b'Exterior Sweep', b'Exterior Sweep')], max_length=80)),
                ('completion_time', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='api.Event')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('acronym', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=30)),
                ('longitude', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Universities',
            },
        ),
        migrations.AddField(
            model_name='nationals',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nationals', to='api.Organization'),
        ),
        migrations.AddField(
            model_name='nationals',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='identity',
            unique_together=set([('first_name', 'last_name', 'gender', 'dob')]),
        ),
        migrations.AddField(
            model_name='host',
            name='nationals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='api.Nationals'),
        ),
        migrations.AddField(
            model_name='host',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='api.Organization'),
        ),
        migrations.AddField(
            model_name='host',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='api.University'),
        ),
        migrations.AddField(
            model_name='host',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guestregistration',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='api.Identity'),
        ),
        migrations.AddField(
            model_name='flag',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='api.Host'),
        ),
        migrations.AddField(
            model_name='flag',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='api.Identity'),
        ),
        migrations.AddField(
            model_name='flag',
            name='nationals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='api.Nationals'),
        ),
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.Host'),
        ),
        migrations.AddField(
            model_name='administrator',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrators', to='api.University'),
        ),
        migrations.AddField(
            model_name='administrator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='guestregistration',
            unique_together=set([('identity', 'event')]),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set([('host', 'name', 'date')]),
        ),
        migrations.AlterUniqueTogether(
            name='carboncopyaddress',
            unique_together=set([('user', 'email')]),
        ),
    ]
